Repository kubernetes-sigs/cluster-api-provider-docker, pull requests merged in 2019-08, with the labels that each got.

#140 Generate DockerCluster with kubebuilder
  PROJECT
  api/v1alpha2/dockercluster_types.go
  api/v1alpha2/groupversion_info.go
  api/v1alpha2/zz_generated.deepcopy.go
  cmd/manager/main.go
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_dockerclusters.yaml
  config/crd/patches/webhook_in_dockerclusters.yaml
  controllers/dockercluster_controller.go
  controllers/suite_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#144 use cluster-api mapfunc
  controllers/dockermachine_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#149 fixes errors seen in verify-govet
  hack/update-deps.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#147 Use cluster api map function
  controllers/dockermachine_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#148 controller logic
  actuators/actuators.go
  actuators/cluster.go
  actuators/machine.go
  api/v1alpha2/dockermachine_types.go
  api/v1alpha2/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachines.yaml
  config/rbac/role.yaml
  controllers/dockermachine_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#155 Fix NPEs in capdctl
  .gitignore
  cmd/capdctl/main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#161 Fix ownerref match
  controllers/dockermachine_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#159 register capi types with manager
  cmd/manager/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#157 Make container restartable in non-docker runtime
  .gitignore
  Dockerfile
  config/default/manager_image_patch.yaml-e
  config/manager/manager.yaml
  hack/verify-boilerplate.sh
  third_party/forked/README.md
  third_party/forked/loadbalancer/README.md
  third_party/forked/rerun-process-wrapper/LICENSE
  third_party/forked/rerun-process-wrapper/README.md
  third_party/forked/rerun-process-wrapper/restart.sh
  third_party/forked/rerun-process-wrapper/start.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#156 Add a MacOS step in the getting started secton of the README
  README.md
  examples/simple-cluster.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#162 DOC: clarify what registry means
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#165 Adds a DockerCluster.Status.Ready field
  api/v1alpha2/dockercluster_types.go
  api/v1alpha2/dockermachine_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachines.yaml
  config/rbac/role.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XL

#166 Pin controller-gen version
  Makefile
  config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachines.yaml
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#138 Add myself as a maintainer
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#168 Adds APIEndpoints to docker cluster
  api/v1alpha2/dockercluster_types.go
  api/v1alpha2/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclusters.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#167 Set docker cluster as ready to allow CAPI to proceed
  controllers/dockercluster_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#142 Cloud init adapter for kind
  cloudinit/doc.go
  cloudinit/kindadapter.go
  cloudinit/kindadapter_test.go
  cloudinit/rumcmd.go
  cloudinit/runcmd_test.go
  cloudinit/writefiles.go
  cloudinit/writefiles_test.go
  go.mod
  kind/actions/cluster_actions.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#169 Copy cloudinit packages to build manager binary
  Dockerfile
  hack/verify-all.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#170 docs: Create a compatible kind cluster, and troubleshoot an incompatible one
  docs/kind.md
  docs/troubleshooting.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#175 Add capdctl, capd-manager versions to bug report template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#174 Use v0.1 image (latest image from release-0.1 branch) instead of latest image
  cmd/capdctl/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#173 Refactor DockerMachineReconcile to use CAPI util function
  controllers/dockermachine_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#171 reconcileDelete DockerMachine
  api/v1alpha2/dockermachine_types.go
  controllers/dockermachine_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#164 Reconcile ELB in cluster controller
  controllers/dockercluster_controller.go
  controllers/dockermachine_controller.go
  kind/actions/kind.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#176 docs: Create a compatible kind cluster, and troubleshoot an incompatible one
  docs/kind.md
  docs/troubleshooting.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#179 fix: enable status endpoints
  api/v1alpha2/dockercluster_types.go
  api/v1alpha2/dockermachine_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachines.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#177 Add capdctl, capd-manager versions to bug report template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#183 Call klog init
  cmd/manager/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#184 Fix logger name for machine controller
  cmd/manager/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#180 chore: switch from Update() to Patch()
  .gitignore
  controllers/dockermachine_controller.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#186 Fixes a tiny typo in the build instructions
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#187 Fix to broken simple-cluster
  examples/simple-cluster.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#189 Bump klog from v0.3.1 to v0.4.0
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#185 Refactor the create function
  controllers/dockermachine_controller.go
  go.mod
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#190 Update to latest cluster-api
  cmd/manager/main.go
  config/default/manager_auth_proxy_patch.yaml
  controllers/dockercluster_controller.go
  controllers/dockermachine_controller.go
  go.mod
  go.sum
  objects/cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#192 Use utils
  controllers/dockermachine_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#193 Reduce scope and refactor
  cmd/capdctl/main.go
  cmd/kind-test/main.go
  config/rbac/role.yaml
  controllers/dockercluster_controller.go
  controllers/dockermachine_controller.go
  go.mod
  go.sum
  kind/actions/kind.go
  kind/controlplane/create.go
  kind/controlplane/kubeconfig.go
  kind/nodes.go
  objects/all.go
  objects/capi.go
  objects/cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#196 Cloud config
  Dockerfile
  cloudinit/kindadapter.go
  cloudinit/kindadapter_test.go
  cloudinit/rumcmd.go
  cloudinit/runcmd_test.go
  cloudinit/writefiles.go
  cloudinit/writefiles_test.go
  controllers/dockercluster_controller.go
  controllers/dockermachine_controller.go
  docker/actions/cluster_actions.go
  docker/actions/kind.go
  docker/constants/constants.go
  docker/kubeadm/config.go
  docker/nodes.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#197 Insert --ignore-preflight-errors=all into kubeadm commands
  cloudinit/rumcmd.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#198 hack kubeadm ignore errors
  cloudinit/rumcmd.go
  cloudinit/runcmd_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#199 Make CreateControlPlane use cloud-init
  controllers/dockercluster_controller.go
  docker/actions/cluster_actions.go
  docker/actions/kind.go
  docker/kubeadm/config.go
  docker/nodes.go
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#202 Use patch helper from cluster-api
  .gitignore
  api/v1alpha2/zz_generated.deepcopy.go
  controllers/dockercluster_controller.go
  controllers/dockermachine_controller.go
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#200 Make cluster controller like CAPA awsCluster controller
  api/v1alpha2/dockercluster_types.go
  controllers/dockercluster_controller.go
  docker/loadbalancer.go
  docker/nodes.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#204 Add detiber as project admin
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#207 Do not requeue while waiting for watched resources
  controllers/dockermachine_controller.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#205 🐛 Fix DockerMachine delete for first control plane
  docker/actions/cluster_actions.go
  docker/actions/kind.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#206 ✨ Add cluster-api category
  api/v1alpha2/dockercluster_types.go
  api/v1alpha2/dockermachine_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_dockerclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachines.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#209 Add storage version to api tyupes
  api/v1alpha2/dockercluster_types.go
  api/v1alpha2/dockermachine_types.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#212 Fixup YAML for kustomize v3.1.x
  config/default/kustomization.yaml
  config/rbac/kustomization.yaml
  config/webhook/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#201 cloudinit adapter clean up
  cloudinit/kindadapter.go
  cloudinit/rumcmd.go
  cloudinit/runcmd_test.go
  cloudinit/unknown.go
  cloudinit/unknown_test.go
  cloudinit/writefiles.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#214 Check if nodes.List returned an error
  docker/actions/cluster_actions.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#213 Kustomize fixes
  config/certmanager/kustomization.yaml
  config/crd/kustomization.yaml
  config/manager/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#215 remove unused source code and scripts
  .goreleaser.yml
  cmd/versioninfo/versioninfo.go
  scripts/build-binaries.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#217 Fix controlplane init
  docker/nodes.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#210 refactor machine controller
  controllers/dockercluster_controller.go
  controllers/dockermachine_controller.go
  docker/actions/cluster_actions.go
  docker/actions/kind.go
  docker/constants/constants.go
  docker/loadbalancer.go
  docker/machine.go
  docker/nodes.go
  docker/util.go
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#226 🏃‍♂️ Add 'help' target to Makefile and make it the default
  Makefile
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#225 🏃‍♂️ Move manager to project root
  Dockerfile
  Dockerfile.dev
  Makefile
  hack/verify-docker-build.sh
  main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#232 Adds makefile target to generate release notes
  Makefile
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#234 ✨ Update PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#233 ✨ Adds DockerMachineTemplate type to support MachineDeployment/Sets
  api/v1alpha2/dockermachinetemplate_types.go
  api/v1alpha2/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#235 📖 Update the README
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#236 :sparkles: Commit machinetemplate CRD
  config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinetemplates.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#237 🏃‍♂️ Name v1alpha2 imports
  main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#231 ✨ Add DockerMachine.Spec.CustomImage for customizing the container image the node runs
  api/v1alpha2/dockermachine_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachines.yaml
  controllers/dockermachine_controller.go
  docker/machine.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#238 :running: Fix some genfiles
  config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachinetemplates.yaml
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M
