Repository kubernetes-sigs/cluster-api-provider-docker, pull requests merged in 2019-07, with the labels that each got.

#46 Build images with dev tag by default
  scripts/publish-manager.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#51 Fix kubeconfig fetching steps in readme
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#48 Update publish-manager to be more non gcp friendly
  README.md
  scripts/publish-manager.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#27 Add logger to actuators
  actuators/cluster.go
  actuators/machine.go
  cmd/capd-manager/main.go
  go.mod
  logger/logger.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#59 Add logger package to build container
  Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#57 update go mod files
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XS

#53 Cluster reconciliation should reconcile exited ELB
  actuators/actuators.go
  actuators/cluster.go
  actuators/machine.go
  kind/actions/kind.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#56 remove `kind` the binary as a dependnecy
  Dockerfile
  README.md
  actuators/machine.go
  cmd/capdctl/main.go
  cmd/kind-test/main.go
  execer/client.go
  go.mod
  go.sum
  hack/verify-gofmt.sh
  kind/actions/cluster_actions.go
  kind/actions/kind.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#64 Typo in capdctl --help
  cmd/capdctl/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#62 All the fixes for cluster api v0.1.4
  README.md
  actuators/actuators.go
  actuators/machine.go
  cmd/capd-manager/main.go
  cmd/capdctl/main.go
  kind/actions/cluster_actions.go
  kind/actions/kind.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#68 Feedback from a recent PR I forgot to push
  actuators/actuators.go
  cmd/capd-manager/main.go
  kind/actions/cluster_actions.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#71 Fix typo
  kind/actions/cluster_actions.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#72 Create main.workflow
  .github/main.workflow
Labels: approved, cncf-cla: yes, lgtm, size/S

#75 Build container image on all pushes and publish image on push to master
  .github/main.workflow
Labels: approved, cncf-cla: yes, lgtm, size/S

#79 Fix the name of the image in the github action
  .github/main.workflow
Labels: approved, cncf-cla: yes, lgtm, size/XS

#76 make 6443 as a constant
  kind/actions/cluster_actions.go
  kind/actions/kind.go
  kind/constants/constants.go
  kind/kubeadm/config.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#80 a better tagging strategy
  .github/main.workflow
Labels: approved, cncf-cla: yes, lgtm, size/S

#81 Minor fixup for workflow
  .github/main.workflow
Labels: approved, cncf-cla: yes, lgtm, size/XS

#77 Add verify-docker-build to pre-submit tests
  hack/verify-all.sh
  hack/verify-docker-build.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#83 Log errors on verify failure
  hack/verify-all.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#85 Update capi base image and drop support for <v0.1.6
  cmd/capdctl/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#86 Fix logging panic
  logger/logger.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#84 Refactor capdctl
  cmd/capd-manager/main.go
  cmd/capdctl/main.go
  go.mod
  go.sum
  kind/controlplane/create.go
  kind/controlplane/kubeconfig.go
  objects/all.go
  objects/capi.go
  objects/cluster.go
  objects/control_plane.go
  objects/rbac.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#91 Fix panics
  Dockerfile
  cmd/capd-manager/main.go
  cmd/capdctl/main.go
  cmd/kind-test/main.go
  logger/logger.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#92 Capi bump
  cmd/capd-manager/main.go
  cmd/capdctl/main.go
  examples/simple-cluster.yaml
  objects/cluster.go
  objects/control_plane.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#89 Implement version info into binaries
  README.md
  cmd/capd-manager/main.go
  cmd/capdctl/main.go
  cmd/kind-test/main.go
  cmd/versioninfo/versioninfo.go
  hack/set-workspace-status.sh
  scripts/build-binaries.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#97 Clean up verification tools
  hack/verify-all.sh
  hack/verify-gofmt.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#95 Release
  .github/main.workflow
  .github/release.workflow
  .gitignore
  .goreleaser.yml
  Dockerfile
  cmd/capd-manager/main.go
  cmd/versioninfo/versioninfo.go
  hack/set-workspace-status.sh
  hack/verify-docker-build.sh
  hack/verify-goimports.sh
  scripts/build-binaries.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#99 Fix release workflow
  .github/release.workflow
Labels: approved, cncf-cla: yes, lgtm, size/XS

#100 correctly name github workflow
  .github/main.workflow
Labels: approved, cncf-cla: yes, lgtm, size/XS

#101 Use a GITHUB_TOKEN secret
  .github/main.workflow
Labels: approved, cncf-cla: yes, lgtm, size/XS

#102 configure gcloud for docker
  .github/main.workflow
Labels: approved, cncf-cla: yes, lgtm, size/XS

#103 Attempt to push the images after running goreleaser
  .github/main.workflow
  .goreleaser.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#104 actually run push images
  .github/main.workflow
Labels: approved, cncf-cla: yes, lgtm, size/XS

#105 revamp of tag and push workflow
  .github/main.workflow
  .goreleaser.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#106 quote the environment
  .github/main.workflow
Labels: approved, cncf-cla: yes, lgtm, size/XS

#108 build outside of goreleaser
  .github/main.workflow
  .goreleaser.yml
  Dockerfile
  hack/verify-all.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#111 fix up the workflow
  .github/main.workflow
Labels: approved, cncf-cla: yes, lgtm, size/XS

#112 add runs back in
  .github/main.workflow
Labels: approved, cncf-cla: yes, lgtm, size/XS

#114 Manual release of container images
  .github/main.workflow
  .goreleaser.yml
  docs/release.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#115 Release 0.1
  .github/main.workflow
  .gitignore
  .goreleaser.yml
  Dockerfile
  cmd/capd-manager/main.go
  cmd/versioninfo/versioninfo.go
  docs/release.md
  hack/set-workspace-status.sh
  hack/verify-all.sh
  hack/verify-docker-build.sh
  hack/verify-gofmt.sh
  hack/verify-goimports.sh
  scripts/build-binaries.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#116 fixup goreleaser
  .goreleaser.yml
  Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#120 Rename capd-manager to manager
  .goreleaser.yml
  Dockerfile
  README.md
  hack/verify-all.sh
  hack/verify-docker-build.sh
  scripts/build-binaries.sh
  scripts/publish-manager.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#126 Change imports from v1alpha1 to v1alpha2
  actuators/actuators.go
  actuators/cluster.go
  actuators/machine.go
  cmd/capd-manager/main.go
  go.mod
  go.sum
  objects/cluster.go
  objects/rbac.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#128 Break `capdctl setup` into `capdctl kind` and `capdctl platform`
  cmd/capdctl/main.go
  kind/controlplane/create.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#129 [0.1] Break `capdctl setup` into `capdctl kind` and `capdctl platform`
  cmd/capdctl/main.go
  kind/controlplane/create.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#122 basic kubebuilder
  Dockerfile
  Makefile
  PROJECT
  api/v1alpha1/dockermachine_types.go
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/zz_generated.deepcopy.go
  cmd/manager/main.go
  config/certmanager/certificate.yaml
  config/certmanager/kustomization.yaml
  config/certmanager/kustomizeconfig.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachines.yaml
  config/crd/kustomization.yaml
  config/crd/kustomizeconfig.yaml
  config/crd/patches/cainjection_in_dockermachines.yaml
  config/crd/patches/webhook_in_dockermachines.yaml
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_image_patch.yaml
  config/default/manager_image_patch.yaml-e
  config/default/manager_prometheus_metrics_patch.yaml
  config/default/manager_webhook_patch.yaml
  config/default/webhookcainjection_patch.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/rbac/auth_proxy_role.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/kustomization.yaml
  config/rbac/leader_election_role.yaml
  config/rbac/leader_election_role_binding.yaml
  config/rbac/role.yaml
  config/rbac/role_binding.yaml
  config/samples/infrastructure_v1alpha1_dockermachine.yaml
  config/webhook/kustomization.yaml
  config/webhook/kustomizeconfig.yaml
  config/webhook/manifests.yaml
  config/webhook/service.yaml
  controllers/dockermachine_controller.go
  controllers/suite_test.go
  go.mod
  go.sum
  hack/boilerplate.go.txt
  hack/fetch_bins.sh
  hack/verify-golint.sh
  hack/verify-gotest.sh
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#130 Ignore invalid samples
  .gitignore
  config/samples/infrastructure_v1alpha1_dockermachine.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#124 Fix capdctl to work with v1alpha2 infrastructure
  cmd/capdctl/main.go
  go.mod
  go.sum
  kind/controlplane/create.go
  objects/all.go
  objects/capi.go
  objects/control_plane.go
  objects/rbac.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#141 Adds ProviderID
  Makefile
  api/v1alpha1/dockermachine_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_dockermachines.yaml
  go.sum
  hack/verify-boilerplate.sh
Labels: approved, cncf-cla: yes, lgtm, size/L
