Repository kubernetes-sigs/cluster-api-provider-docker, pull requests merged in 2019-09, with the labels that each got.

#240 Updates KinD packages to 0.5.1 🐛
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#242 🏃 Adds dockermachinetemplates to the kustomization manifest
  config/crd/kustomization.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#244 ✨ Watch dockercluster
  controllers/dockermachine_controller.go
  controllers/dockermachine_controller_test.go
  go.mod
Labels: approved, cncf-cla: yes, lgtm, size/L

#245 🐛 Copy over hack/tools go mod workaround from cluster-api
  hack/tools/go.mod
  hack/tools/go.sum
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#247 Made SyncPeriod configurable
  main.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#249 🐛 Remove capdctl version from issue template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#253 ✨ Notify when failing back to default container image
  docker/machine.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#248 📖 Update simple-cluster example to v1alpha2
  examples/simple-cluster.yaml
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L
