Repository kubernetes-sigs/cluster-api-provider-docker, pull requests merged in 2019-06, with the labels that each got.

#7 docs: update readme
  README.md
  examples/simple-cluster.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#2 Several updates
  README.md
  actuators/machine.go
  cmd/capdctl/main.go
  cmd/kind-test/main.go
  kind/actions/cluster_actions.go
  kind/actions/kind.go
  kind/kubeadm/config.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#10 Dockerfile: use the name of the project as working directory
  Dockerfile
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, priority/backlog, size/XS

#14 Fix the build
  cmd/kind-test/main.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#11 README: modify the build step for binaries
  .gitignore
  README.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, priority/backlog, size/S

#3 Adds security contacts
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, size/S

#12 go-modules: fix build, module name and local imports
  actuators/actuators.go
  actuators/machine.go
  cmd/capd-manager/main.go
  cmd/capdctl/main.go
  cmd/kind-test/main.go
  go.mod
  go.sum
  kind/actions/cluster_actions.go
  kind/actions/kind.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, priority/backlog, size/S

#16 fix import paths
  actuators/actuators.go
  actuators/machine.go
  cmd/capd-manager/main.go
  cmd/capdctl/main.go
  cmd/kind-test/main.go
  go.mod
  go.sum
  kind/actions/cluster_actions.go
  kind/actions/kind.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#20 Add CONTRIBUTING.md file
  CONTRIBUTING.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#25 update readme
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#26 small refactor for actuator folder
  actuators/actuators.go
  actuators/cluster.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#30 configure machine deployment
  README.md
  cmd/capdctl/main.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#34 Provide patch to events to the cluster-api system account
  cmd/capdctl/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#44 Fix up the secret name
  actuators/actuators.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#35 change variable names
  actuators/machine.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#39 Temporary fix for cluster-api 1.4
  actuators/actuators.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#41 Fixup the provider id
  actuators/machine.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#45 Fix provisioner name
  .gitignore
  cmd/capd-manager/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#37 Fixup rbac for v0.1.4
  cmd/capdctl/main.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#47 Add issue and pr templates from capa
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#50 Update capdctl subcommands help
  cmd/capdctl/main.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
